### ISSUE TITLE
运行WhatsStar

### ISSUE THREAD

**Issue by LLLLLea** [StrickYan/WhatsStar#1]
你好，我对你的“测试明星脸”的小程序特别感兴趣，请问运行的话，是把这些代码down下来，放在微信小程序开发者工具里吗？

**Comment by 137220** [comment]
@LLLLLea 代码分为两部分。一部分是微信客户端代码，这部分放在微信开发者工具里跑；另一部分是服务端代码，PHP编写，所以你需要把这部分部署到可以运行php的服务器上。这两部分代码你需要适配的地方是把工程里涉及到服务器域名的地方改成你自己部署的服务器域名或ip。
